<?php

return [
    'admin_email' => env('ADMIN_EMAIL', 'admin@quranvisuals.com'),

    'keywords' => [
        'quran',
        'qur\'an',
        'quran recitation',
        'surah',
        'surat',
        'tilawah',
        'tilawat',
        'murottal',
        'murotal',
        'qari',
        'imam',
        'recitation',
        'ayat',
        'ayah',
        // Arabic keywords
        'قرآن',
        'قران',
        'سورة',
        'تلاوة',
        'تلاوه',
        'مرتل',
        'ترتيل',
        'تجويد',
        'قارئ',
        'الحرم',
        'رمضان',
        'آية',
        'آيات',
        'الشيخ',
    ],
    'blocked_keywords' => [
        'remix',
        'instrumental',
        'lofi',
        'beats',
        'mix',
        'cover',
        'karaoke',
        'music',
    ],
    'allowed_channels' => [
        // Add trusted YouTube channel names here to allow regardless of keywords.
        // Example: 'Quranic Recitations',
    ],
    'allowed_audio_extensions' => [
        'mp3',
        'm4a',
        'wav',
        'ogg',
    ],
    'presets' => [
        [
            'id' => 'noir-cinema',
            'name' => 'Noir Cinema',
            'vars' => [
                '--bg-1' => '#0b0b0d',
                '--bg-2' => '#141318',
                '--bg-3' => '#1b1a22',
                '--accent' => '#c28b3b',
                '--accent-2' => '#6f4b1f',
            ],
            'layers' => [
                ['effect' => 'gradientGlow', 'params' => ['color' => '#c28b3b']],
                ['effect' => 'concentricArcs', 'params' => ['color' => '#c28b3b', 'count' => 5]],
                ['effect' => 'particles', 'params' => ['color' => '#ffffff', 'count' => 40, 'shape' => 'square']],
                ['effect' => 'waveLine', 'params' => ['color' => '#6f4b1f']],
            ],
        ],
        [
            'id' => 'neon-lounge',
            'name' => 'Neon Lounge',
            'vars' => [
                '--bg-1' => '#0a0f18',
                '--bg-2' => '#0f1f2e',
                '--bg-3' => '#112638',
                '--accent' => '#18f0c7',
                '--accent-2' => '#ff6b6b',
            ],
            'layers' => [
                ['effect' => 'gradientGlow', 'params' => ['color' => '#18f0c7']],
                ['effect' => 'pulseRing', 'params' => ['color' => '#18f0c7']],
                ['effect' => 'particles', 'params' => ['color' => '#18f0c7', 'count' => 80, 'shape' => 'circle']],
                ['effect' => 'waveLine', 'params' => ['color' => '#18f0c7']],
                ['effect' => 'waveLine', 'params' => ['color' => '#ff6b6b', 'yPosition' => 0.65]],
            ],
        ],
        [
            'id' => 'desert-twilight',
            'name' => 'Desert Twilight',
            'vars' => [
                '--bg-1' => '#0b0d14',
                '--bg-2' => '#121623',
                '--bg-3' => '#1c2231',
                '--accent' => '#c9975b',
                '--accent-2' => '#7a4f2a',
            ],
            'layers' => [
                ['effect' => 'gradientGlow', 'params' => ['color' => '#c9975b']],
                ['effect' => 'starField', 'params' => ['color' => '#c9975b', 'count' => 100]],
                ['effect' => 'geometricMandala', 'params' => ['color' => '#7a4f2a', 'sides' => 8]],
                ['effect' => 'waveLine', 'params' => ['color' => '#c9975b']],
            ],
        ],
        [
            'id' => 'studio-black',
            'name' => 'Studio Black',
            'vars' => [
                '--bg-1' => '#050505',
                '--bg-2' => '#0e0e10',
                '--bg-3' => '#151618',
                '--accent' => '#7f8cff',
                '--accent-2' => '#3d45a8',
            ],
            'layers' => [
                ['effect' => 'gradientGlow', 'params' => ['color' => '#7f8cff']],
                ['effect' => 'verticalBars', 'params' => ['color' => '#7f8cff', 'count' => 48]],
                ['effect' => 'particles', 'params' => ['color' => '#a78bfa', 'count' => 25, 'shape' => 'circle']],
                ['effect' => 'concentricArcs', 'params' => ['color' => '#a78bfa', 'count' => 3]],
            ],
        ],
        [
            'id' => 'sacred-garden',
            'name' => 'Sacred Garden',
            'vars' => [
                '--bg-1' => '#060d08',
                '--bg-2' => '#0a1a0e',
                '--bg-3' => '#102016',
                '--accent' => '#4ae08a',
                '--accent-2' => '#1a7a42',
            ],
            'layers' => [
                ['effect' => 'gradientGlow', 'params' => ['color' => '#4ae08a']],
                ['effect' => 'nebulaClouds', 'params' => ['color' => '#1a7a42']],
                ['effect' => 'starField', 'params' => ['color' => '#ffffff', 'count' => 70]],
                ['effect' => 'particles', 'params' => ['color' => '#4ae08a', 'count' => 50, 'shape' => 'circle']],
                ['effect' => 'waveLine', 'params' => ['color' => '#4ae08a']],
            ],
        ],
    ],
    'yt_dlp_binary' => 'yt-dlp',
];
